# Generated by Django 5.0.1 on 2024-01-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idaluno', models.AutoField(db_column='idAluno', primary_key=True, serialize=False)),
                ('nomealuno', models.CharField(db_column='nomeAluno', max_length=255)),
                ('datainiciotreino', models.DateField(blank=True, db_column='dataInicioTreino', null=True)),
                ('situacaocadastro', models.CharField(db_column='situacaoCadastro', max_length=50)),
            ],
            options={
                'db_table': 'aluno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoriafundamento',
            fields=[
                ('idcategoriafundamento', models.AutoField(db_column='idCategoriaFundamento', primary_key=True, serialize=False)),
                ('desc_categoriafundamento', models.CharField(db_column='desc_categoriaFundamento', max_length=255)),
            ],
            options={
                'db_table': 'categoriaFundamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fundamento',
            fields=[
                ('idfundamento', models.AutoField(db_column='idFundamento', primary_key=True, serialize=False)),
                ('desc_fundamento', models.CharField(db_column='desc_Fundamento', max_length=255)),
                ('idcategoriafundamento', models.ForeignKey(blank=True, db_column='idCategoriaFundamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Avaliacoes.categoriafundamento')),
            ],
            options={
                'db_table': 'fundamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ratingaluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idatributo', models.IntegerField(blank=True, db_column='idAtributo', null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('idaluno', models.ForeignKey(blank=True, db_column='idAluno', null=True, on_delete=django.db.models.deletion.CASCADE, to='Avaliacoes.aluno')),
                ('idfundamento', models.ForeignKey(blank=True, db_column='idFundamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Avaliacoes.fundamento')),
            ],
            options={
                'db_table': 'ratingAluno',
                'managed': True,
            },
        ),
    ]
