# Generated by Django 5.0.1 on 2024-01-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idaluno', models.AutoField(db_column='idAluno', primary_key=True, serialize=False)),
                ('nomealuno', models.CharField(db_column='nomeAluno', max_length=255)),
                ('datainiciotreino', models.DateField(blank=True, db_column='dataInicioTreino', null=True)),
                ('situacaocadastro', models.CharField(db_column='situacaoCadastro', max_length=50)),
            ],
            options={
                'db_table': 'aluno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaFundamento',
            fields=[
                ('idcategoriafundamento', models.AutoField(db_column='idCategoriaFundamento', primary_key=True, serialize=False)),
                ('desc_categoriafundamento', models.CharField(db_column='desc_categoriaFundamento', max_length=255)),
            ],
            options={
                'db_table': 'categoriaFundamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fundamento',
            fields=[
                ('idfundamento', models.AutoField(db_column='idFundamento', primary_key=True, serialize=False)),
                ('desc_fundamento', models.CharField(db_column='desc_Fundamento', max_length=255)),
                ('idcategoriafundamento', models.ForeignKey(blank=True, db_column='idCategoriaFundamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Avaliacoes.categoriafundamento')),
            ],
            options={
                'db_table': 'fundamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AtributoFundamento',
            fields=[
                ('idatributo', models.IntegerField(db_column='idAtributo', primary_key=True, serialize=False)),
                ('desc_atributofundamento', models.CharField(db_column='desc_atributoFundamento', max_length=45)),
                ('fk_idfundamento', models.ForeignKey(db_column='fk_idFundamento', on_delete=django.db.models.deletion.RESTRICT, to='Avaliacoes.fundamento')),
            ],
            options={
                'db_table': 'atributoFundamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('idaluno', models.ForeignKey(db_column='idAluno', on_delete=django.db.models.deletion.CASCADE, to='Avaliacoes.aluno')),
                ('idatributo', models.ForeignKey(db_column='idAtributo', on_delete=django.db.models.deletion.CASCADE, to='Avaliacoes.atributofundamento')),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': True,
                'unique_together': {('idaluno', 'idatributo')},
            },
        ),
    ]
