# Generated by Django 5.0.1 on 2024-01-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributofundamento',
            name='fk_idfundamento',
            field=models.ForeignKey(blank=True, db_column='fk_idFundamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Avaliacoes.fundamento'),
        ),
    ]
